### ISSUE TITLE
TypeError: Cannot read property 'userRequest' of null

### ISSUE THREAD

**Issue by denispasin** [guess-js/guess#152] opened 2019-07-13 00:12 UTC
Building this with GatsbyJS but this is probably not related to it. At build time it got stuck with this error. Apparently, my module can be `null`.

Comes from this line:
https://github.com/guess-js/guess/blob/8c37974494cb649e1f71f491a73f136cf39b61f2/packages/guess-webpack/src/prefetch-plugin.ts#L52

Is there a weird thing in my config/page generation?

**Comment by mgechev** [comment] 2019-07-15 20:19
@denispasin do you have a demo where I can reproduce the problem?

**Comment by mgechev** [comment] 2019-07-23 02:58
@denispasin https://github.com/guess-js/guess/commit/dbee867a355392c8a722c2df550c6359f59fc22c should have fixed this. Would you give it a try with 0.3.8?

**Comment by mgechev** [comment] 2019-07-30 03:36
Closing. Feel free to comment/open a new issue of the problem is not resolved.

**Closed by mgechev** 2019-07-30 03:36 UTC

**Comment by denispasin** [comment] 2019-08-02 23:21
@mgechev Finally had the time to test this morning. That seems to fix it! Thanks a lot! (I had to rollback a "few" commits 'cause I found a way around it in the mean time)

**Comment by mgechev** [comment] 2019-08-03 02:18
🚀
