### ISSUE TITLE
Angular routing modules error on build

### ISSUE THREAD

**Issue by morganpizzini** [guess-js/guess#199] opened 2019-08-29 05:37 UTC
When using an application with multiples routings module, one imported as 'forRoot', others 'forChild', the build goes wrong with 
```
GuessPlugin(node:16444) UnhandledPromiseRejectionWarning: Error: Multiple root routing modules found
```

Here the source code
https://github.com/morganpizzini/guess-test

The guide I follow
https://www.youtube.com/watch?v=5FRxQiGqqmM

**Comment by mgechev** [comment] 2019-08-29 06:08
Thanks for the repro! This would be really helpful!

**Comment by nicobytes** [comment] 2019-09-04 15:15
I have the same error!
![Screen Shot 2019-09-04 at 10 13 17 AM](https://user-images.githubusercontent.com/7611944/64267842-b4afa080-cefc-11e9-84b3-d1b9cbc880e4.png)

```
Angular CLI: 8.3.2
Node: 12.9.1
OS: darwin x64
Angular: 8.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.2
@angular-devkit/build-angular     0.803.2
@angular-devkit/build-optimizer   0.803.2
@angular-devkit/build-webpack     0.803.2
@angular-devkit/core              8.3.2
@angular-devkit/schematics        8.3.2
@angular/cdk                      8.1.4
@angular/cli                      8.3.2
@angular/fire                     5.2.1
@angular/material                 8.1.4
@angular/pwa                      0.803.2
@ngtools/webpack                  8.3.2
@schematics/angular               8.3.2
@schematics/update                0.803.2
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
```

**Comment by mgechev** [comment] 2019-09-04 22:06
Would you provide a minimal reproduction as well? I want to make sure both errors are caused by the same routing structure.

**Comment by mgechev** [comment] 2019-09-10 17:40
It should be easy to fix this. @nicobytes, what you need in this case is to parse the routes witht:

```
import { parseAngularRoutes } from 'guess-parser';

parseAngularRoutes('PATH_TO_TS_CONFIG', ['module1.ts', 'module2.ts']);
```
The second argument of `parseAngularRouets` is a list of modules to ignore as root ones. In the process of parsing your routing tree, Guess.js needs to find a single root routing module so it can start building your route definitions. For example:

```
// root.ts
{
  path: '',
  loadChildren: 'module#Foo'
}

// module1.ts
{
  path: 'foo',
  loadChildren: 'module#Bar'
},
{
  path: '',
  redirectTo: 'foo'
}

// module2.ts
{
  path: 'bar',
  loadChildren: 'module#Baz'
},
{
  path: '',
  redirectTo: 'bar'
}
```

This way Guess.js knows that you have the following route: `/foo/bar`.

**Comment by morganpizzini** [comment] 2019-09-10 18:06
I think, me and @nicobytes got the same issue, probably related to the new 'loadchildren' method. Can you try to implement the solution on my repo or provide us a solution using 'import().then()' syntax?
Thank you

**Comment by mgechev** [comment] 2019-09-10 20:02
Above I used `loadChildren` set to string for simplicity. For Guess.js it doesn't matter. Just add the modules different from your root module to the exclude array in `parseAngularRoutes`.

**Comment by mgechev** [comment] 2019-09-15 05:22
Let me know if the second argument of `parseAngularRoutes` does not help. Closing for now.

**Closed by mgechev** 2019-09-15 05:22 UTC

**Comment by morganpizzini** [comment] 2019-09-20 05:37
Hi, I just test it, and the second arguments seems to not be allowed in `parseAngularRoutes`. Where I should import and call that function? There is no documentation about that.
Could you make a PR to my repository with the solution? At the moment the sample has just two modules: `FirstModule` and `SecondModule`. The build script is `npm run build:guess`. 
Thank you
