### ISSUE TITLE
Fail when login with Google when using guess-webpack

### ISSUE THREAD

**Issue by thangman22** [guess-js/guess#80] opened 2018-09-26 10:44 UTC
I try to using guess-webpack with my nuxt.js. When I serve my project my browser is open Google login page. When login complete and redirect back to localhost:xxxxx < some random port this page is empty. How I fix it?

**Comment by mgechev** [comment] 2018-09-26 18:42
Would you be able to share logs or a video of your experience? I'm not able to get the entire picture of what's going wrong.

Exact steps to reproduce the problem would be very helpful as well.

**Comment by thangman22** [comment] 2018-10-03 08:44
This is screenshot of this bug
https://imgur.com/rJNPkyP

**Comment by zipme** [comment] 2018-10-10 15:36
same here

**Comment by mgechev** [comment] 2018-10-10 17:53
Unfortunately, I cannot reproduce this issue. You can double-check the GA view ID and your access rights to it.

We'll work on better error reporting in `guess-ga`. Hopefully we'll be able to figure out what went wrong then.

**Comment by zipme** [comment] 2018-10-10 21:40
@mgechev it seems to be working now, but everytime I restart the server I need to re-authenticate with google account, is there away to avoid this? Or do I need to use the `jwt` option? If so what should I put in there? 

Thanks!

**Comment by mgechev** [comment] 2018-10-10 21:45
If you specify `startDate` & `endDate` `guess-webpack` will be able to cache the GA report. For reference see [this](https://github.com/mgechev/guess-js-react-demo/blob/master/config/webpack.config.prod.js#L330-L345).

**Comment by zipme** [comment] 2018-10-10 22:13
@mgechev Brilliant! It works! And may I ask how does it cache the report? Because I am deploying my app via docker, so the build will happen in the docker container, how do I handle the authentication there?

**Comment by mgechev** [comment] 2018-10-10 22:19
You can set the [`jwt`](https://github.com/guess-js/guess/blob/master/packages/guess-webpack/src/guess-webpack.ts#L17) property for this purpose.

You can follow [this](http://2ality.com/2015/10/google-analytics-api.html) tutorial to get it in a JSON format. Once you get the file, just set it as value to the `jwt` property in the object literal you pass to the `GuessPlugin`.

**Comment by mgechev** [comment] 2018-10-28 01:02
Closing this issue. Let me know if you're still experiencing problems.

**Closed by mgechev** 2018-10-28 01:02 UTC
