### ISSUE TITLE
Angular9 Unable to extract routes from application.

### ISSUE THREAD

**Issue by mustordont** [guess-js/guess#335] opened 2020-02-15 12:07 UTC
1. Created new angular9 app
2. Added SSR:
> ng add @nguniversal/express-engine

3. Added lazy-load module:
> $ ng g m test --route test --module app

4. Moved routes from separate routing module to the main lazy-load module: [test.module.ts](https://github.com/mustordont/nguniversal-guess-routes/blob/master/src/app/test/test.module.ts)

5. Run:
> npm run prerender

guess-js throws: 
> Unable to extract routes from application.

Affects only Windows machines
Reproduction: https://github.com/mustordont/nguniversal-guess-routes

**Comment by mgechev** [comment] 2020-02-16 04:13
Thanks for providing the repro! I'll try to look at it next week.

**Comment by kuncevic** [comment] 2020-02-18 00:36
I had the same issue, prerender always throwing `Unable to extract routes from application` and I am on MAC, this error didn't happen like before RC.9 or something

**Comment by kuncevic** [comment] 2020-02-18 00:39
I had the same issue, prerender always throwing `Unable to extract routes from application` 

![image](https://user-images.githubusercontent.com/1283734/74694197-40b34b80-5243-11ea-9cbf-122c318fef94.png)


This error started like after RC.8 or RC.9. However I've got my app prerendering with no issues though.

**Comment by c3mohamn** [comment] 2020-02-28 21:04
Having the same issue. 

It's breaking in the mapping starting at line 535 in [angular/index.ts](https://github.com/guess-js/guess/blob/master/packages/guess-parser/src/angular/index.ts#L535
).

**Comment by mgechev** [comment] 2020-03-02 19:11
@kuncevic, @c3mohamn can you provide a sample project where I can reproduce the issue?

**Comment by kuncevic** [comment] 2020-07-29 23:25
Just migrated to v10 all seems good

**Comment by mgechev** [comment] 2020-07-31 21:00
Closing for now. Free free to open a new issue if the problem is not resolved.

**Closed by mgechev** 2020-07-31 21:00 UTC
Labels: bug, help wanted
